### PR TITLE
fix: add missing origin request header

### PR DESCRIPTION
**Pull request by sagibb**
The final booking post request now needs an origin header or else it fails with an Internal Server Error.

- [x] add origin header to post request

### CODE REVIEW

**Review by robgreenberg3 — DISMISSED** [review]
LGTM

**Comment by Alkaar** [comment]
Appreciate the fix @sagibb! So I tested this out and I see the origin header is only needed for the final post request. You made the change where every request will pass the origin header. If you are ok with it, could you make the change only for the post request where it's needed? It makes it easier in the long run so I don't assume origin is needed for every request in case I need to revisit this code again.

The place to make the change is a few lines above where you made the current change. See below.

Change from...
```scala
        createHeaders(resyKeys) :+ "Content-Type" -> "application/x-www-form-urlencoded": _*
```

to...

```scala
        createHeaders(resyKeys) ++ Seq(
          "Content-Type" -> "application/x-www-form-urlencoded",
          "origin"       -> "https://widgets.resy.com/"
        ): _*
```

Also, you don't need the `s` before the string. The `s` denotes string interpolation if there are variables in the string which in this case, there are none.

**Review by Alkaar — CHANGES_REQUESTED** [review]
Appreciate the fix @sagibb! So I tested this out and I see the origin header is only needed for the final post request. You made the change where every request will pass the origin header. If you are ok with it, could you make the change only for the post request where it's needed? It makes it easier in the long run so I don't assume origin is needed for every request in case I need to revisit this code again.

The place to make the change is a few lines above where you made the current change. See below.

Change from...
```scala
        createHeaders(resyKeys) :+ "Content-Type" -> "application/x-www-form-urlencoded": _*
```

to...

```scala
        createHeaders(resyKeys) ++ Seq(
          "Content-Type" -> "application/x-www-form-urlencoded",
          "origin"       -> "https://widgets.resy.com/"
        ): _*
```

Also, you don't need the `s` before the string. The `s` denotes string interpolation if there are variables in the string which in this case, there are none.

**Comment by sagibb** [comment]
@Alkaar done

**Review by Alkaar — APPROVED** [review]
🚀

**Pull request merged**
